apiVersion: v1
data:
  parsers.conf: |-
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Flush 1
        Daemon Off
        Log_Level info
        Parsers_File parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser docker
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On*

    [FILTER]
        Name modify
        Match *
        Rename message content
        Rename log content

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Merge_Log_Trim On
        Labels Off
        Annotations Off
        K8S-Logging.Parser Off
        K8S-Logging.Exclude Off


    [FILTER]
        Name nest
        Match kube.*
        Operation lift
        Nested_under kubernetes
        Add_prefix   kubernetes_

    [FILTER]
        Name grep
        Match kube.*
        Exclude kubernetes_container_name fluent-bit

    [FILTER]
        Name modify
        Match kube.*
        Rename log content
        Rename kubernetes_pod_name k8s.pod.name
        Rename kubernetes_namespace_name k8s.namespace.name
        Remove kubernetes_container_image
        Remove kubernetes_docker_id
        Remove kubernetes_container_name
        Remove kubernetes_pod_id
        Remove kubernetes_host
        Remove time
        Remove kubernetes_container_hash
        Add k8s.cluster.name Onlineboutique

    [FILTER]
        Name     throttle
        Match    kube.*
        Rate     5000
        Window   5
        Print_Status true
        Interval 30s

    [OUTPUT]
        Name http
        Match kube.*
        host <HOST OF THE DYNATRACE ACTIVE GATE>
        port 9999
        URI /e/bix24852/api/v2/logs/ingest
        header Authorization Api-Token <DYNATRACE API TOKEN>
        header Content-Type application/json; charset=utf-8
        Format json
        allow_duplicated_headers false
        Json_date_key timestamp
        Json_date_format iso8601
        tls On
        tls.verify Off
        Retry_Limit false

    [OUTPUT]
        Name stdout
        Match kube.*
        Format json
        Json_date_key timestamp
        Json_date_format iso8601


kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 1.7.9
    helm.sh/chart: fluent-bit-0.15.15
  name: fluent-bit
  namespace: default

